name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tests
      run: |
        sudo pip3 install setuptools && \
        sudo pip3 install -r test-requirements.txt && \
        pytype --exclude=faucetconfrpc_pb2_grpc.py --exclude=faucetconfrpc_pb2.py . && \
        pylint --ignore=faucetconfrpc_pb2_grpc.py,faucetconfrpc_pb2.py *py && \
        pytest test_faucetconfrpc.py && \
        ./test_faucetconfrpc.py && \
        docker build -f Dockerfile.server .
