name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tests
      env:
        PYTHONPATH: "."
        GO111MODULE: "on"
      run: |
        go get github.com/square/certstrap && \
        PATH=~/go/bin:$PATH certstrap -v && \
        sudo pip3 install setuptools && \
        sudo pip3 install -r test-requirements.txt && \
        ./codecheck.sh && \
        PATH=~/go/bin:$PATH pytest ./test_faucetconfrpc.py && \
        docker build -f Dockerfile.server .
