name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tests
      run: |
        pip3 install setuptools wheel && \
        pip3 install -r test-requirements.txt && \
        python3 -m pytype *py && \
        python3 -m pylint *py && \
        docker build -f Dockerfile.server .
